name: Workflow with Email Identifier

on:
  # Runs when manually triggered
  workflow_dispatch:
  # Also runs on push to main branch
  push:
    branches: [ main ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
      - name: entertheymail
        run: echo "Repo test"
        
      - name: Display date
        run: date
